steps:
  #Build client image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-appengine-demo', './client']
  #Push client image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcp-appengine-demo']
  #Deploy image
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', "--image-url=gcr.io/${PROJECT_ID}/gcp-appengine-demo", "./client/client.yaml"]
    timeout: '1600s'
  #Build api image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcp-appengine-demo', './api']
  #Push api image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gcp-appengine-demo']
  #Deploy api
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', "--image-url=gcr.io/${PROJECT_ID}/gcp-appengine-demo", "./api/api.yaml"]
    timeout: '1600s'
images:
  - gcr.io/$PROJECT_ID/gcp-appengine-demo
  - gcr.io/$PROJECT_ID/gcp-appengine-demo-api