steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/db-grad/gcp-appengine-demo', '.']
images: ['gcr.io/db-grad/gcp-appengine-demo']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  timeout: '1600s'